### ISSUE TITLE
Helm chart should not include a hard dependency on kwasm operator

### ISSUE THREAD

**Issue by endocrimes** [spinkube/spin-operator#108]
Although many will lifecycle their nodes through kwasm, we don't depend on their CRDs, and some will want to have specific (statically configured) node pools.

We should not explicitly depend on kwasm while that is the case (especially until `runtime-class-manager` is ready).

**Comment by vdice** [comment]
We now maintain the values.yaml for the spin-operator chart (i.e. we don't use the auto-generated version from helmify).

Thoughts on retaining the option of installing kwasm-operator but defaulting to not installed?  The nice part about having the option is we can bake in our own node-installer image version that would be compatible with a given release, so if users would like to install the kwasm-operator, they wouldn't need to manually configure the installer image.

```yaml
## kwasm-operator configuration overrides can be added below.
## See https://github.com/KWasm/kwasm-operator/blob/main/charts/kwasm-operator/values.yaml
kwasm-operator:
  enabled: false
  kwasmOperator:
    installerImage: ghcr.io/spinkube/containerd-shim-spin/node-installer:<version>
```
