### ISSUE TITLE
The operator crashes when providing an empty string for a value in 'sqliteDatabases' using runtime config

### ISSUE THREAD

**Issue by mikkelhegn** [spinkube/spin-operator#174]
This deployment makes the spin-operator crash:

```yaml
apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: sql
spec:
  image: ttl.sh/sql-app:1h
  replicas: 1
  executor: containerd-shim-spin
  runtimeConfig:
    sqliteDatabases:
      - name: "sqlite"
        type: "libsql"
        options:
          - name: "url"
            value: "http://sqld:8080"
          - name: "token"
            value: ""
```

Changing to this does not:

```yaml
apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: sql
spec:
  image: ttl.sh/sql-app:1h
  replicas: 1
  executor: containerd-shim-spin
  runtimeConfig:
    sqliteDatabases:
      - name: "sqlite"
        type: "libsql"
        options:
          - name: "url"
            value: "http://sqld:8080"
          - name: "token"
            value: "NOT EMPTY!!!!"
```

Operator logs:

```
2024-03-12T23:06:41Z	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "spinapp", "controllerGroup": "core.spinoperator.dev", "controllerKind": "SpinApp", "SpinApp": {"name":"sql","namespace":"default"}, "namespace": "default", "name": "sql", "reconcileID": "518879da-640c-4456-b580-43d99dbf88ae"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x106d498]

goroutine 211 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:116 +0x1a4
panic({0x11d9c00?, 0x2238390?})
	/usr/local/go/src/runtime/panic.go:770 +0x124
github.com/spinkube/spin-operator/internal/runtimeconfig.renderOptionsIntoMap({0x40003aab40, 0x6}, {0x40003aab10, 0x7}, {0x4000200730, 0x2, 0x400083f848?}, 0x4000498330, 0x4000498360)
	/workspace/internal/runtimeconfig/types.go:103 +0xf8
github.com/spinkube/spin-operator/internal/runtimeconfig.(*Spin).AddSQLiteDatabase(0x4000498450, {0x40003aab20, 0x6}, {0x40003aab40, 0x6}, {0x40003aab10, 0x7}, 0x4000498330, 0x4000498360, {0x4000200730, ...})
	/workspace/internal/runtimeconfig/types.go:70 +0xd4
github.com/spinkube/spin-operator/internal/runtimeconfig.(*K8sBuilder).Build(0x400083fae8, {0x1655280, 0x4000794930}, 0x400073e508)
	/workspace/internal/runtimeconfig/runtime_config.go:143 +0x368
github.com/spinkube/spin-operator/internal/controller.(*SpinAppReconciler).reconcileDeployment(0x4000499110, {0x1655280, 0x4000794930}, 0x400073e508, 0x4000708380)
	/workspace/internal/controller/spinapp_controller.go:232 +0x110
github.com/spinkube/spin-operator/internal/controller.(*SpinAppReconciler).Reconcile(0x4000499110, {0x1655280, 0x4000794930}, {{{0x40003aab10?, 0x5?}, {0x40003aab0c?, 0x400063cd08?}}})
	/workspace/internal/controller/spinapp_controller.go:126 +0x1e0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1658ef8?, {0x1655280?, 0x4000794930?}, {{{0x40003aab10?, 0xb?}, {0x40003aab0c?, 0x0?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:119 +0x8c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0x40004b21e0, {0x16552b8, 0x400043be00}, {0x1252d80, 0x40005179a0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:316 +0x2dc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0x40004b21e0, {0x16552b8, 0x400043be00})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266 +0x16c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:227 +0x74
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 118
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:223 +0x404
```

The equivalent runtime config works in Spin:

```toml
[sqlite_database.sqlite]
type = "libsql"
url = "http://sqld:8080"
token = ""
```
