### ISSUE TITLE
LLM runtime configuration leads to pods not starting

### ISSUE THREAD

**Issue by radu-matei** [spinkube/spin-operator#181]
Creating a Spin application with LLM runtime config leads to `CrashLoopBackOff`:

```
apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: sentiment-analysis-spin
spec:
  image: "ttl.sh/sentiment-analysis:24h"
  executor: containerd-shim-spin
  replicas: 2
  runtimeConfig:
    llmCompute:
      type: "remote_http"
      options:
        - name: "url"
          value: "<my-http-endpoint>"
        - name: "token"
          value: "<i-know-this-should-be-referencing-a-secret>"
```

Replacing with a runtime config file secret leads to the app starting.

**Comment by endocrimes** [comment]
@radu-matei do you have a copy of the generated runtimeConfig by any chance?

**Comment by radu-matei** [comment]
Where would I get it from on the node?

**Comment by endocrimes** [comment]
```console
kubectl get secrets
kubectl get secret app-name-{adler32-hash}
```

**Comment by endocrimes** [comment]
```toml
[[config_provider]]
type = 'env'
prefix = 'SPIN_VARIABLE_'

[llm_compute]
token = '<i-know-this-should-be-referencing-a-secret>'
type = 'remote_http'
url = '<my-http-endpoint>'
```

^ is what i got with your sample - which feels like it _should_ be correct?
