### ISSUE TITLE
Python SPIN App pod fails to start in SpinKube

### ISSUE THREAD

**Issue by camba1** [spinkube/spin-operator#202]
### What Were you doing?
Trying to deploy minimal sample Python SPIN container in SpinKube

### What did you expect?
Container to deploy in SpinKube and start normally

### What happened?
Pod fails to start and reports CrashLoopBackOff status 

### Additional info:
Tried the same thing with  a Go container and that works without issues. So SpinKube deployment was done properly into k3d

### Steps to reproduce:

```bash 
spin new -t http-py --accept-defaults spin-kube-py
cd spin-kube-py 
python -m venv env 
source env/bin/activate 
pip3 install -r requirements.txt
spin up --build
```
At this point the application works normally, now we deploy to k3d

```bash
spin registry push --build bolbeck/py-spin
spin kube deploy --from bolbeck/py-spin 
```

Checking the deployment of the pod:

```bash
kubectl get pods       
```
Pods in CrashLoopBackOff status
```bash
kubectl describe pod py-spin-86c88d45b-r4nzd
```
In the pod description:
 Created container py-spin
 Started container py-spin
 _Back-off restarting failed container py-spin in pod py-spin-86c88d45b-r4nzd_default(305165a0-19a6-4026-98b2-e19c6c8ef850)_

Note that pod logs show do not show anything 

```bash
kubectl describe replicaset py-spin-86c88d45b
```
Error in the replicate set description: _Error creating: Unauthorized_

### Environment
k3d version v5.6.0
k3s version v1.27.5-k3s1 (default)
spin-operator 0.1.0

**Comment by endocrimes** [comment]
Could you paste in the whole kubectl describe output? (Alongside kubectl events?) thanks!

**Comment by camba1** [comment]
Sure thing! I just re-built and re-pushed to k3d to get a fresh set.

Here is the describe pod:

```yaml
Name:                py-spin-86c88d45b-t7xjg
Namespace:           default
Priority:            0
Runtime Class Name:  wasmtime-spin-v2
Service Account:     default
Node:                k3d-wasm-cluster-server-0/172.18.0.3
Start Time:          Sat, 13 Apr 2024 09:33:17 -0500
Labels:              core.spinoperator.dev/app-name=py-spin
                     core.spinoperator.dev/app.py-spin.status=ready
                     pod-template-hash=86c88d45b
Annotations:         <none>
Status:              Running
IP:                  10.42.2.18
IPs:
  IP:           10.42.2.18
Controlled By:  ReplicaSet/py-spin-86c88d45b
Containers:
  py-spin:
    Container ID:  containerd://5cc0054fc98e2a7a75d46eadcf2a6bada0360db878f00506866634c95484d941
    Image:         bolbeck/py-spin
    Image ID:      docker.io/bolbeck/py-spin@sha256:2c8d16c414fe050a430852317546af4fe0b485706e638ce553d8e70b4683e5e8
    Port:          80/TCP
    Host Port:     0/TCP
    Command:
      /
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Sat, 13 Apr 2024 09:33:42 -0500
      Finished:     Sat, 13 Apr 2024 09:33:43 -0500
    Ready:          False
    Restart Count:  2
    Environment:    <none>
    Mounts:
      /runtime-config.toml from spin-runtime-config (ro,path="runtime-config.toml")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vndh9 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  spin-runtime-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  py-spin-760b133c
    Optional:    true
  kube-api-access-vndh9:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  53s                default-scheduler  Successfully assigned default/py-spin-86c88d45b-t7xjg to k3d-wasm-cluster-server-0
  Normal   Pulled     51s                kubelet            Successfully pulled image "bolbeck/py-spin" in 2.467593251s (2.467613084s including waiting)
  Normal   Pulled     43s                kubelet            Successfully pulled image "bolbeck/py-spin" in 430.641583ms (430.664042ms including waiting)
  Normal   Pulling    29s (x3 over 54s)  kubelet            Pulling image "bolbeck/py-spin"
  Normal   Pulled     29s                kubelet            Successfully pulled image "bolbeck/py-spin" in 451.691292ms (451.716584ms including waiting)
  Normal   Created    29s (x3 over 51s)  kubelet            Created container py-spin
  Normal   Started    29s (x3 over 45s)  kubelet            Started container py-spin
  Warning  BackOff    15s (x4 over 43s)  kubelet            Back-off restarting failed container py-spin in pod py-spin-86c88d45b-t7xjg_default(33e98adb-aca5-448c-b331-b122d0f8b53c)
```
And here is the Kube events:

```yaml
LAST SEEN               TYPE      REASON                         OBJECT                         MESSAGE
5h28m (x356 over 17h)   Warning   BackOff                        Pod/py-spin-86c88d45b-hbmwr    Back-off restarting failed container py-spin in pod py-spin-86c88d45b-hbmwr_default(62754499-2370-4dea-8e16-9214f05d1cfd)
54m (x8 over 15h)       Warning   FailedToUpdateEndpoint         Endpoints/py-spin              Failed to update endpoint default/py-spin: Unauthorized
54m (x8 over 15h)       Warning   FailedToUpdateEndpointSlices   Service/py-spin                Error updating Endpoint Slices for Service default/py-spin: failed to update py-spin-x7s7k EndpointSlice for Service default/py-spin: Unauthorized
28m (x49 over 17h)      Normal    Started                        Pod/py-spin-86c88d45b-hbmwr    Started container py-spin
28m (x388 over 17h)     Warning   BackOff                        Pod/py-spin-86c88d45b-r4nzd    Back-off restarting failed container py-spin in pod py-spin-86c88d45b-r4nzd_default(305165a0-19a6-4026-98b2-e19c6c8ef850)
9m18s                   Normal    SuccessfulCreate               ReplicaSet/py-spin-86c88d45b   Created pod: py-spin-86c88d45b-t7xjg
9m18s                   Normal    ScalingReplicaSet              Deployment/py-spin             Scaled up replica set py-spin-86c88d45b to 2
9m18s (x2 over 21h)     Warning   FailedToCreateEndpoint         Endpoints/py-spin              Failed to create endpoint for service default/py-spin: endpoints "py-spin" already exists
9m18s                   Normal    SuccessfulCreate               ReplicaSet/py-spin-86c88d45b   Created pod: py-spin-86c88d45b-sts2w
9m17s                   Normal    Scheduled                      Pod/py-spin-86c88d45b-t7xjg    Successfully assigned default/py-spin-86c88d45b-t7xjg to k3d-wasm-cluster-server-0
9m17s                   Normal    Scheduled                      Pod/py-spin-86c88d45b-sts2w    Successfully assigned default/py-spin-86c88d45b-sts2w to k3d-wasm-cluster-agent-1
9m15s                   Normal    Pulled                         Pod/py-spin-86c88d45b-t7xjg    Successfully pulled image "bolbeck/py-spin" in 2.467593251s (2.467613084s including waiting)
9m14s                   Normal    Pulled                         Pod/py-spin-86c88d45b-sts2w    Successfully pulled image "bolbeck/py-spin" in 3.228073377s (3.22807821s including waiting)
9m8s                    Warning   FailedToUpdateEndpoint         Endpoints/py-spin              Failed to update endpoint default/py-spin: Operation cannot be fulfilled on endpoints "py-spin": the object has been modified; please apply your changes to the latest version and try again
9m7s                    Normal    Pulled                         Pod/py-spin-86c88d45b-sts2w    Successfully pulled image "bolbeck/py-spin" in 434.327167ms (434.361834ms including waiting)
9m7s                    Normal    Pulled                         Pod/py-spin-86c88d45b-t7xjg    Successfully pulled image "bolbeck/py-spin" in 430.641583ms (430.664042ms including waiting)
8m53s                   Normal    Pulled                         Pod/py-spin-86c88d45b-t7xjg    Successfully pulled image "bolbeck/py-spin" in 451.691292ms (451.716584ms including waiting)
8m53s                   Normal    Pulled                         Pod/py-spin-86c88d45b-sts2w    Successfully pulled image "bolbeck/py-spin" in 399.4945ms (399.508959ms including waiting)
8m25s                   Normal    Pulled                         Pod/py-spin-86c88d45b-sts2w    Successfully pulled image "bolbeck/py-spin" in 425.151917ms (425.177959ms including waiting)
8m25s (x4 over 9m14s)   Normal    Created                        Pod/py-spin-86c88d45b-sts2w    Created container py-spin
8m24s (x4 over 9m8s)    Normal    Started                        Pod/py-spin-86c88d45b-sts2w    Started container py-spin
8m24s                   Normal    Pulled                         Pod/py-spin-86c88d45b-t7xjg    Successfully pulled image "bolbeck/py-spin" in 349.710334ms (349.715875ms including waiting)
8m24s (x4 over 9m15s)   Normal    Created                        Pod/py-spin-86c88d45b-t7xjg    Created container py-spin
8m24s (x4 over 9m9s)    Normal    Started                        Pod/py-spin-86c88d45b-t7xjg    Started container py-spin
7m43s (x5 over 9m18s)   Normal    Pulling                        Pod/py-spin-86c88d45b-t7xjg    Pulling image "bolbeck/py-spin"
7m43s                   Normal    Pulled                         Pod/py-spin-86c88d45b-t7xjg    Successfully pulled image "bolbeck/py-spin" in 414.483125ms (414.515375ms including waiting)
7m32s (x5 over 9m18s)   Normal    Pulling                        Pod/py-spin-86c88d45b-sts2w    Pulling image "bolbeck/py-spin"
4m13s (x25 over 9m7s)   Warning   BackOff                        Pod/py-spin-86c88d45b-sts2w    Back-off restarting failed container py-spin in pod py-spin-86c88d45b-sts2w_default(2024ad6b-c5d8-40f6-ad7f-fb4ef70d1c82)
4m6s (x25 over 9m7s)    Warning   BackOff                        Pod/py-spin-86c88d45b-t7xjg    Back-off restarting failed container py-spin in pod py-spin-86c88d45b-t7xjg_default(33e98adb-aca5-448c-b331-b122d0f8b53c)
```

Here is the describe for the replicaset, which interestingly enough does not show an error anymore:

```yaml
Name:           py-spin-86c88d45b
Namespace:      default
Selector:       core.spinoperator.dev/app-name=py-spin,core.spinoperator.dev/app.py-spin.status=ready,pod-template-hash=86c88d45b
Labels:         core.spinoperator.dev/app-name=py-spin
                core.spinoperator.dev/app.py-spin.status=ready
                pod-template-hash=86c88d45b
Annotations:    deployment.kubernetes.io/desired-replicas: 2
                deployment.kubernetes.io/max-replicas: 3
                deployment.kubernetes.io/revision: 1
Controlled By:  Deployment/py-spin
Replicas:       2 current / 2 desired
Pods Status:    2 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  core.spinoperator.dev/app-name=py-spin
           core.spinoperator.dev/app.py-spin.status=ready
           pod-template-hash=86c88d45b
  Containers:
   py-spin:
    Image:      bolbeck/py-spin
    Port:       80/TCP
    Host Port:  0/TCP
    Command:
      /
    Environment:  <none>
    Mounts:
      /runtime-config.toml from spin-runtime-config (ro,path="runtime-config.toml")
  Volumes:
   spin-runtime-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  py-spin-760b133c
    Optional:    true
Events:
  Type    Reason            Age   From                   Message
  ----    ------            ----  ----                   -------
  Normal  SuccessfulCreate  10m   replicaset-controller  Created pod: py-spin-86c88d45b-t7xjg
  Normal  SuccessfulCreate  10m   replicaset-controller  Created pod: py-spin-86c88d45b-sts2w
```

Also, the image can be downloaded from docker hub as it is publicly available (bolbeck/py-spin)
