### ISSUE TITLE
Support Setting Container Environment Variables via SpinApp CRD

### ISSUE THREAD

**Issue by kate-goldenring** [spinkube/spin-operator#248]
Users should be able to set Pod environment variables via the SpinApp CRD. These can be used for configuring settings, such as open telemetry endpoints:
```yaml
env:
 - name: NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
 - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://$(NODE_IP):4318"
```

Proposal: add a `SpinApp.spec.env`

### Workaround
Create deployment directly instead of creating a `SpinApp` CR, bypassing the Spin operator:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spin-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin-test
  template:
    metadata:
      labels:
        app: spin-test
    spec:
      runtimeClassName: wasmtime-spin-v2
      containers:
      - name: spin-test
        image: ttl.sh/spin-foo-123:48h
        command: ["/"]
        ports:
        - containerPort: 80
      env:
     - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
     - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: "http://$(NODE_IP):4318"
```

**Comment by calebschoepp** [comment]
Thanks for filing this @kate-goldenring. `SpinApp.spec.env` is definitely one approach that would work, but I think we should do more design work before we pull the trigger. I'm a little hesitant to set the precedent that users can set whatever env on the underlying pod that they want. This wouldn't necessarily translate well to other executors (granted we do already have a precedent of supporting features that don't work for all executors so maybe I'm over thinking this).

An alternative would be to have something like `SpinApp.spec.otel-env` that only lets you set specific OTel environment variables.

I think we need to spend some time thinking about how OTel will get configured in other executors to figure out the design here.

**Comment by kate-goldenring** [comment]
@calebschoepp I'd rather have a more general solution given that users will likely want to set other env vars as well. I also don't think we have a precedent for specific fields like `otel-env`. I could see this being something that the `spin kube scaffold` plugin abstracts with a flag.

I don't imagine it being too complicated for executors to reference and use the env vars set in the `SpinApp` CRD.

**Comment by calebschoepp** [comment]
> @calebschoepp I'd rather have a more general solution given that users will likely want to set other env vars as well. I also don't think we have a precedent for specific fields like otel-env. I could see this being something that the spin kube scaffold plugin abstracts with a flag.

I like the idea of some kind of `--otel-enabled` flag on the plugin.

> I don't imagine it being too complicated for executors to reference and use the env vars set in the SpinApp CRD.
I'm not concerned about their ability to reference the env vars. I'm concerned executors having no meaningful equivalent.

**Comment by kate-goldenring** [comment]
>  I'm concerned executors having no meaningful equivalent.

I see. I think we are running into an interesting distinction here between two types of environment variables in Spin:
- Environment variable set on the runtime: `OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:4318 spin up`
- Environment variable set in the Wasm instance: `spin up --env key=value`

In the context of the `SpinApp` CRD,  setting `env` in the SpinApp spec I'd assume would map to `spin up --env`. This tells executors to make sure that the environment variables are set in the runtime context of the spin app when it is executed. 

I am coming around to understanding how OTEL is a unique case and should not be set in an `env` field.

**Comment by calebschoepp** [comment]
@kate-goldenring how do you feel about something like this?

Setting `env` on a `SpinApp` sets environment variables in the Wasm runtime context of the spin app when it is executed.

```yaml
apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: simple-spinapp
spec:
  image: "ghcr.io/spinkube/containerd-shim-spin/examples/spin-rust-hello:v0.13.0"
  replicas: 1
  executor: containerd-shim-spin
  env:
    FOO: bar
```
Setting `env` on a `SpinAppExecutor` sets environment variables in the context of where the executor (shim) is running.

```yaml
apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinAppExecutor
metadata:
  name: containerd-shim-spin
spec:
  createDeployment: true
  deploymentConfig:
    runtimeClassName: wasmtime-spin-v2
    installDefaultCACerts: true
  env:
    OTEL_EXPORTER_OTLP_ENDPOINT=http...
```

For clarity we could change the names to be something like `runtimeEnv` and `executorEnv` or something like that. Then you could also set `exectorEnv` from the `SpinApp` and that would override/merge from the executor config. And you could set `runtimeEnv` from the `SpinAppExecutor` and that would set a default value for all `SpinApp`s.
