### ISSUE TITLE
Support configuring AWS configuration values on SpinApp for SQS triggered apps 

### ISSUE THREAD

**Issue by kate-goldenring** [spinkube/spin-operator#362]
The [Spin SQS Trigger](https://github.com/fermyon/spin-trigger-sqs) expects the following AWS configuration variables to be set in the environment at start up:
- `AWS_DEFAULT_REGION`
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
- `AWS_SESSION_TOKEN`

We could support configuring these by updating the SpinApp CRD to contain an `sqs` section:

```
spec:
  createDeployment: true
  deploymentConfig:
    runtimeClassName: wasmtime-spin-v2
    sqs:
      - aws_default_region: us-west-2
      - aws_secret_access_key:
            valueFrom:
              secretKeyRef:
                name: "my-super-secret"
                key: "turso-token"
```

Alternatively, the trigger could be updated to get these values from runtime config instead: https://github.com/fermyon/spin-trigger-sqs/issues/52
